In order to suppress some deprecations warning :
odolbeau/phone-number-bundle pull request #109
Opened 2022-05-18 10:27 UTC by GLacourt

Enforce type declarations.
Add strict types declaration.
Update php minimum requirement.
Add composer vulnerability package

2022-05-18 11:26 UTC, jderusse requested changes

2022-05-18 11:26 UTC, jderusse commented on src/Doctrine/DBAL/Types/PhoneNumberType.php
> +use function gettype;
the project don't import functions

2022-05-18 11:26 UTC, jderusse commented on composer.json
> +        "roave/security-advisories": "dev-latest",
please revert

2022-06-17 10:35 UTC, Nek- commented on src/Doctrine/DBAL/Types/PhoneNumberType.php
> +declare(strict_types=1);
This may be a regression as well

2022-07-01 16:53 UTC, Nek- commented
Hello @GLacourt and thank you for your contribution. However you was not answering to our comments so I took the liberty to make another PR containing your changes but with a scope at the project level. https://github.com/odolbeau/phone-number-bundle/pull/120

Let me know if something looks wrong to you inside this.

2022-07-04 07:17 UTC, closed without merging